<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pivi" nsURI="http:///asu/ser/capstone/pivi.ecore" nsPrefix="asu.ser.capstone.pivi">
  <eClassifiers xsi:type="ecore:EClass" name="IfEnd" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="IfStart" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPort">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        eOpposite="#//Statement/inputs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputPort" eType="#//OutputPort"
        eOpposite="#//OutputPort/inputPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instructions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodEnd" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="MethodStart" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPort">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        eOpposite="#//Statement/outputs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPort" eType="#//InputPort"
        eOpposite="#//InputPort/outputPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PiviDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//Start"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPort" upperBound="-1"
        eType="#//InputPort" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Start">
    <eStructuralFeatures xsi:type="ecore:EReference" name="startPort" upperBound="-1"
        eType="#//StartPort" eOpposite="#//StartPort/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartPort">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        eOpposite="#//Statement/start"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//Start"
        eOpposite="#//Start/startPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" upperBound="-1"
        eType="#//StartPort" containment="true" resolveProxies="false" eOpposite="#//StartPort/statement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//InputPort" containment="true" resolveProxies="false" eOpposite="#//InputPort/statement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//OutputPort" containment="true" resolveProxies="false" eOpposite="#//OutputPort/statement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhileEnd" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="WhileStart" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
